### PR TITLE
Frontend refactor complete

### PR DESCRIPTION
**Pull request by EnzoMartin**
Resolves issue #43

I wasn't able to test mobile as IIS Express wouldn't cooperate with me, but it _should_ be working, with some minor adjustments needed

### CODE REVIEW

**Comment by ghost** [comment]
I'm looking at it from my Android phone and it looks and works great, good job!

**Comment by wbbarr** [comment]
Apparently we should not be using this on a cellular network due to intense data usage.

**Comment by sichinumi** [comment]
Yep. By my rough calculations, leaving this up for an hour at the default 1Hz refresh rate uses up approximately 100 megabytes of data.

**Comment by ghost** [comment]
I have unlimited data, but surely we can minimize the data somehow? Seems like a lot, 100 mb for just a few chat messages?

**Comment by wbbarr** [comment]
It is a lot, and when we move to websockets, we’re going to cut down on that quite a bit.

**Pull request merged**
